paper_reference: 'CTRL: Clustering Training Losses for Label Error Detection'
implementation_reference: chang-yue/ctrl clustering.compute_mask
method_type: training_assisted_data_processing
loss_epochs: 2
moving_average_size: 3
clamp_losses: true
loss_thresh_factor: 1.0
n_clusters_options:
- 2
- 3
- 4
n_windows_options:
- 1
- 2
- 4
n_clusters: 6
noisy_clusters: 1
num_windows: 1
window_threshold: 2.0
action: downweight
downweight_value: 0.02
