paper_reference: 'GoodCore: Data-effective and Data-efficient Machine Learning through
  Coreset Selection over Incomplete Data'
method_type: data_processing
subset_fraction: 0.1
subset_size: 1522
min_per_class: 1
coreset_fraction: 0.1
per_class: true
h_sample_size: 8
goodcore_batch_size: 95
batch_greedy_size: 95
utility_eval_size: 0
weighting: unit
